### ISSUE TITLE
Restore Not Working?

### ISSUE THREAD

**Issue by brianantonelli** [spikegrobstein/mcwrapper#29]
I'm not sure if this issue is on my end or not but I thought would share. I untarred a backup I made with mcwrapper and then executed a restore:

`mcwrapper restore ~/tmp/20130203042423`

It begins the restore process and then errors out:

`/Library/Ruby/Gems/1.8/gems/mcwrapper-1.6.1/lib/../libexec/mcwrapper: line 975: server_is_running: command not found`

Any ideas?

**Comment by spikegrobstein** [comment]
Hi Brian,

Ack. You're right. I missed a spot when I changed the name of that function.

I just pushed a fix and released 1.6.2

if you update mcwrapper with the following command, you should be ok to restore:

```
gem install mcwrapper -v 1.6.2
```

Please confirm that that fixes it.

Thanks!

**Comment by spikegrobstein** [comment]
you know something, I had a bad feeling that I didn't properly fix it and it turned out to be true.

I'm doing a deep-dive to ensure that restoration works 100%. I hadn't fully tested it since I initially added the feature and apparently enough has changed that it doesnt' work right.

I'll post again when it works. thanks for pointing this out!

**Comment by spikegrobstein** [comment]
Ok, now restore is working and 1.6.3 has been released. I just tested this a bunch.

If you're using a non-standard name for your world directory in your old backups, the restore will probably fail as I changed some of the logic in there to fix the bug.

If that's the case, you can restore manually (all your old backups are still good, the restore process was the part with the error) by copying out the backup file's 'world' directory (whatever you called it) into your minecraft server's directory and restarting minecraft_server.jar.

Let me know if you've got issues and I'll do what I can to help you.

Sorry about all the confusion!

**Comment by brianantonelli** [comment]
Thanks for the update! I'll try this out tonight. Are you looking for any help with this project? I saw you had a OSX preference pane on your todo list which I dont mind helping with.

**Comment by spikegrobstein** [comment]
Yes, I'd love some help on this.

The prefpane I think should probably be a separate project. I had started work on it and got the UI working and had a hack for calling the launchd stuff, but wasn't really satisfied with it. I haven't done serious Cocoa development since around 2002/2003. I'm not entirely sure what happened to that codebase, actually.

Hit me up on me@spike.cx to discuss further.

**Comment by brianantonelli** [comment]
Sounds good - just emailed you.
